### ISSUE TITLE
similarMoviesBlock variable return an array of elements that's why you can't use '(similarMoviesBlock).contain(name)' in lesson5task.ts 

### ISSUE THREAD

**Issue by karusya** [StartITProtractorJS/5-startit-movie-finder-bolids#1]
await expect(similarMoviesBlock).contain(name) - here you have an array of elements and trying to extract string of it

**Comment by bolids** [comment]
now that task modified and contain:

let similarMoviesBlock = $$('div.row.is-flex > div.col-md-2> movie-card');  
await browser.wait(EC.visibilityOf(similarMoviesBlock.first()), 2000, 'movie details have not uploaded')
expect(await similarMoviesBlock.count()).to.be.above(0)
