### ISSUE TITLE
Remove debug logging from job output

### ISSUE THREAD

**Issue by Xotabu4** [StartITProtractorJS/5-startit-movie-finder-bolids#2]
It does not provide any info, please clean up your job output

![image](https://user-images.githubusercontent.com/3033972/36720201-ff77a010-1baf-11e8-85c4-65a6504710dd.png)

**Comment by bolids** [comment]
What doest it mean? 
Is it due extra console.log rows in previous code?

**Comment by bolids** [comment]
done
