### ISSUE TITLE
3 protractor config files, 3 npm tasks - replace with one config and one npm task

### ISSUE THREAD

**Issue by Xotabu4** [StartITProtractorJS/5-startit-movie-finder-bolids#3]
package.json:
```
 "test": "protractor ./protractor.conf.js --directConnect=true",
 "test-HW3": "protractor ./HwFromLesson3/protractor.conf.js --directConnect=true",
 "test-Pages": "protractor ./Pages/protractor.conf.js --directConnect=true",
```

3 different tasks that run different groups of tests, travis task work only with first config file:
```
 "test-travis": "protractor ./protractor.conf.js --seleniumAddress=\"http://ip-5236.sunline.net.ua:4444/wd/hub\""
```
![image](https://user-images.githubusercontent.com/3033972/36721075-8dd6ea80-1bb2-11e8-8945-3065ab67e264.png)

- [x] Leave only 1 protractor config file,
- [x] Move files into folders, rename if needed
- [x] leave only `npm test` task that would run all tests

**Comment by bolids** [comment]
leave only npm test task that would run all tests in this way?
https://www.screencast.com/t/zIOVSPmvIh

**Comment by Xotabu4** [comment]
Sorry, keep `test-travis` as well

**Comment by bolids** [comment]
thanks, done
